<?php

namespace Database\Seeders;

use App\Models\Incident;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class IncidentSeeder extends Seeder
{
    public function run(): void
    {
        Incident::insert([
            [
                'category_id' => 1,
                'incident_at' => Carbon::now()->subDays(2),
                'long' => '106.827153',
                'lat' => '-6.175110',
                'location' => 'Monas, Jakarta',
                'related_name' => 'PT. Aman Sentosa',
                'related_status' => 'Dilaporkan',
                'severity' => 'Tinggi',
                'description' => 'Kabel putus akibat cuaca buruk, mengakibatkan pemadaman listrik di area sekitar.',
                'handling_steps' => 'Petugas dikerahkan ke lokasi dan perbaikan sedang dilakukan.',
                'photo_url' => 'https://placehold.co/150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'incident_at' => Carbon::now()->subDays(1)->setTime(10, 45),
                'long' => '110.369490',
                'lat' => '-7.795580',
                'location' => 'Malioboro, Yogyakarta',
                'related_name' => 'CV. Jogja Bersih',
                'related_status' => 'Selesai',
                'severity' => 'Sedang',
                'description' => 'Kebocoran pipa ditemukan di bawah jalan utama. Air menggenangi jalan dan mengganggu lalu lintas.',
                'handling_steps' => 'Pipa diperbaiki dan jalan dikeringkan oleh tim teknis.',
                'photo_url' => 'https://placehold.co/150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'incident_at' => Carbon::now()->subHours(5),
                'long' => '107.609810',
                'lat' => '-6.914744',
                'location' => 'Gedung Sate, Bandung',
                'related_name' => 'Dinas PU',
                'related_status' => 'Proses',
                'severity' => 'Rendah',
                'description' => 'Jalan berlubang menyebabkan kecelakaan kecil pada pengendara motor.',
                'handling_steps' => 'Polisi sudah memasang tanda peringatan. Penambalan jalan dijadwalkan malam ini.',
                'photo_url' => 'https://placehold.co/150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'incident_at' => Carbon::now()->subDays(3),
                'long' => '106.84513',
                'lat' => '-6.20876',
                'location' => 'Sudirman, Jakarta',
                'related_name' => 'PLN Jakarta Selatan',
                'related_status' => 'Dilaporkan',
                'severity' => 'Tinggi',
                'description' => 'Ledakan gardu listrik menyebabkan kebakaran kecil di sekitar area.',
                'handling_steps' => 'Kebakaran berhasil dipadamkan. Investigasi penyebab sedang berlangsung.',
                'photo_url' => 'https://placehold.co/150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'incident_at' => Carbon::now()->subHours(10),
                'long' => '112.75083',
                'lat' => '-7.25747',
                'location' => 'Tunjungan Plaza, Surabaya',
                'related_name' => 'CV. Air Sejahtera',
                'related_status' => 'Selesai',
                'severity' => 'Sedang',
                'description' => 'Saluran air mampet menyebabkan banjir di area parkir bawah tanah.',
                'handling_steps' => 'Pompa air dinyalakan dan saluran dibersihkan.',
                'photo_url' => 'https://placehold.co/150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'incident_at' => Carbon::now()->subDays(4),
                'long' => '98.67690',
                'lat' => '3.58965',
                'location' => 'Lapangan Merdeka, Medan',
                'related_name' => 'Dinas Perhubungan',
                'related_status' => 'Proses',
                'severity' => 'Rendah',
                'description' => 'Lampu lalu lintas tidak berfungsi pada jam sibuk.',
                'handling_steps' => 'Tim teknis sedang memperbaiki panel kontrol.',
                'photo_url' => 'https://placehold.co/150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'incident_at' => Carbon::now()->subMinutes(90),
                'long' => '100.3600',
                'lat' => '-0.9471',
                'location' => 'Pantai Padang',
                'related_name' => 'PDAM Padang',
                'related_status' => 'Dilaporkan',
                'severity' => 'Sedang',
                'description' => 'Pipa air pecah menyebabkan aliran air terganggu ke 3 kecamatan.',
                'handling_steps' => 'Tim sedang melakukan penggalian dan persiapan penggantian pipa.',
                'photo_url' => 'https://placehold.co/150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'incident_at' => Carbon::now()->subHours(2),
                'long' => '122.5167',
                'lat' => '-3.9778',
                'location' => 'Kendari Mall',
                'related_name' => 'PT. Sultra Power',
                'related_status' => 'Proses',
                'severity' => 'Tinggi',
                'description' => 'Pemadaman listrik tanpa pemberitahuan menyebabkan gangguan aktivitas perkantoran.',
                'handling_steps' => 'Sedang dilakukan pengecekan trafo dan jaringan.',
                'photo_url' => 'https://placehold.co/150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'incident_at' => Carbon::now()->subDays(6),
                'long' => '140.7031',
                'lat' => '-2.5337',
                'location' => 'Abepura, Jayapura',
                'related_name' => 'Dinas Lingkungan Hidup',
                'related_status' => 'Selesai',
                'severity' => 'Rendah',
                'description' => 'Sampah menumpuk di area publik akibat keterlambatan pengangkutan.',
                'handling_steps' => 'Sampah sudah dibersihkan dan jadwal pengangkutan diperbaiki.',
                'photo_url' => 'https://placehold.co/150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'incident_at' => Carbon::now()->subDays(5)->setTime(7, 30),
                'long' => '104.0075',
                'lat' => '1.1170',
                'location' => 'Nagoya Hill, Batam',
                'related_name' => 'BP Batam',
                'related_status' => 'Dilaporkan',
                'severity' => 'Sedang',
                'description' => 'Kebocoran gas ringan terdeteksi di pusat kuliner, tidak ada korban.',
                'handling_steps' => 'Area diamankan dan kebocoran ditutup.',
                'photo_url' => 'https://placehold.co/150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
